#=================================================#
# MARS: MinION Assembly and Reporting System      #
# https://github.com/eclarke/mars                 #
#=================================================#

import sys
from pkg_resources import resource_filename

from snakemake.utils import min_version, update_config, validate
from snakemake.exceptions import WorkflowError
import mars

min_version("5.2")

samples = mars.parse_samples(config['samplesheet_fp'])

rule usage:
    message: "Hello there!"

include: resource_filename("mars", "snakemake/processing.rules")
include: resource_filename("mars", "snakemake/assembling.rules")
