#
# MARS: Minion Assembly and Reporting System
# ----------------------------------------------------------------------
#
# This is the head file that imports the actual workflows. It also
# loads the samplesheet and resolves all paths in the config file.

from pkg_resources import resource_filename

import snakemake.utils
import mars

snakemake.utils.min_version("5.4")

samples = mars.parse_samples(config['samplesheet_fp'])
config = mars.resolve_paths(config)

output_dir = config['output_dir'] + '/'
working_dir = output_dir + 'workspace/'
reports_dir = output_dir + 'reports/'

rule list_workflows:
    message:
        (
            "\nAvailable workflows:\n"
            " - process_all: basecall, demultiplex and filter reads, and assess run stats\n"
            " - assemble_all: assemble contigs from each sample and assess assembly quality\n"
            " - polish_all: polish all assemblies and assess polished assembly quality\n"
            "Run a workflow with `mars run <configfile> <workflow>`"
        )

include: resource_filename("mars", "snakemake/process.smk")
include: resource_filename("mars", "snakemake/assemble.smk")
include: resource_filename("mars", "snakemake/polish.smk")
