#=================================================#
# MARS: MinION Assembly and Reporting System      #
# https://github.com/eclarke/mars                 #
#=================================================#

import sys
from pkg_resources import resource_filename

import snakemake.utils
import mars

snakemake.utils.min_version("5.2")

samples = mars.parse_samples(config['samplesheet_fp'])

include: resource_filename("mars", "snakemake/processing.rules")
include: resource_filename("mars", "snakemake/assembling.rules")
